# Generated by Django 5.2.7 on 2025-10-17 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Klasifikasi',
                'verbose_name_plural': 'Klasifikasi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpeditionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('email', 'Email'), ('fisik', 'Fisik')], default='email', max_length=20)),
                ('destination', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('proof_file', models.FileField(blank=True, upload_to='expedition/proofs/%Y/%m/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_via', models.CharField(choices=[('fisik', 'Fisik'), ('email', 'Email')], default='fisik', max_length=10)),
                ('origin', models.CharField(max_length=255, verbose_name='Asal Surat')),
                ('origin_number', models.CharField(max_length=100, verbose_name='Nomor Asal')),
                ('origin_date', models.DateField(verbose_name='Tanggal Surat Asal')),
                ('subject', models.CharField(max_length=300, verbose_name='Perihal')),
                ('priority', models.CharField(choices=[('B', 'Biasa'), ('S', 'Segera'), ('SS', 'Sangat Segera')], default='B', max_length=2)),
                ('scan_pdf', models.FileField(help_text='Hasil scan PDF', upload_to='incoming/scans/%Y/%m/')),
                ('agenda_number', models.CharField(blank=True, help_text='Diisi otomatis via signal saat simpan pertama kali.', max_length=30, unique=True)),
                ('barcode_image', models.ImageField(blank=True, upload_to='incoming/barcodes/')),
                ('qr_image', models.ImageField(blank=True, upload_to='incoming/qrcodes/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REG', 'Terdaftar'), ('DISP', 'Didisposisi'), ('PROG', 'Dalam Proses'), ('DONE', 'Selesai'), ('ARCH', 'Arsip')], default='REG', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retention_class', models.CharField(blank=True, help_text='Kode retensi (mis. JRA)', max_length=50)),
                ('retention_until', models.DateField(blank=True, null=True)),
                ('disposed_at', models.DateField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(blank=True, to='core.attachment')),
                ('classification_tags', models.ManyToManyField(blank=True, to='core.classificationtag')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_created', to=settings.AUTH_USER_MODEL)),
                ('current_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handling_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ND', 'Nota Dinas'), ('UD', 'Undangan'), ('ST', 'Surat Tugas'), ('MM', 'Memo'), ('LN', 'Lainnya')], default='ND', max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='incoming/followups/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='core.incomingletter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('allow_parallel', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.disposition')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispo_sent', to=settings.AUTH_USER_MODEL)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='core.incomingletter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutgoingLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('ND', 'Nota Dinas'), ('UD', 'Undangan'), ('ST', 'Surat Tugas'), ('MM', 'Memo'), ('LN', 'Lainnya')], default='ND', max_length=2)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('number', models.CharField(blank=True, help_text='Akan terisi saat status FINAL (lock nomor).', max_length=40, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review/Paraf'), ('APPROVED', 'Disetujui'), ('FINAL', 'Final (Nomor Terkunci)'), ('SENT', 'Terkirim'), ('ARCH', 'Arsip')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_pdf', models.FileField(blank=True, upload_to='outgoing/signed/%Y/%m/')),
                ('qr_image', models.ImageField(blank=True, upload_to='outgoing/qrcodes/%Y/%m/')),
                ('retention_class', models.CharField(blank=True, max_length=50)),
                ('retention_until', models.DateField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(blank=True, to='core.attachment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.outgoingletter')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DispositionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispo_tasks', to=settings.AUTH_USER_MODEL)),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.disposition')),
            ],
            options={
                'ordering': ['assignee__username'],
                'unique_together': {('disposition', 'assignee')},
            },
        ),
        migrations.AddIndex(
            model_name='incomingletter',
            index=models.Index(fields=['agenda_number'], name='core_incomi_agenda__372f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingletter',
            index=models.Index(fields=['status', 'created_at'], name='core_incomi_status_b4e5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingletter',
            index=models.Index(fields=['origin_date'], name='core_incomi_origin__61970f_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoingletter',
            index=models.Index(fields=['status', 'created_at'], name='core_outgoi_status_cc984f_idx'),
        ),
        migrations.AddIndex(
            model_name='outgoingletter',
            index=models.Index(fields=['number'], name='core_outgoi_number_33a379_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewstep',
            unique_together={('letter', 'order')},
        ),
    ]
