# Generated by Django 5.2.7 on 2025-10-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersuratanPortal',
            fields=[
            ],
            options={
                'verbose_name': 'Persuratan (UI)',
                'verbose_name_plural': 'Persuratan (UI)',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.incomingletter',),
        ),
    ]
