# Generated by Django 5.2.7 on 2025-10-20 02:38

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_persuratanportal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Anexu', 'verbose_name_plural': 'Anexu'},
        ),
        migrations.AlterModelOptions(
            name='classificationtag',
            options={'ordering': ['name'], 'verbose_name': 'Klasifikasaun', 'verbose_name_plural': 'Klasifikasaun'},
        ),
        migrations.AlterModelOptions(
            name='disposition',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dispozisaun', 'verbose_name_plural': 'Dispozisaun'},
        ),
        migrations.AlterModelOptions(
            name='dispositionassignment',
            options={'ordering': ['assignee__username'], 'verbose_name': 'Distribuisaun Dispozisaun', 'verbose_name_plural': 'Distribuisaun Dispozisaun'},
        ),
        migrations.AlterModelOptions(
            name='expeditionrecord',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Rejistu Ekspedisaun', 'verbose_name_plural': 'Rejistu Ekspedisaun'},
        ),
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Asaun Tuir Mai', 'verbose_name_plural': 'Asaun Tuir Mai'},
        ),
        migrations.AlterModelOptions(
            name='incomingletter',
            options={'ordering': ['-created_at'], 'verbose_name': 'Karta Tama', 'verbose_name_plural': 'Karta Tama'},
        ),
        migrations.AlterModelOptions(
            name='outgoingletter',
            options={'ordering': ['-created_at'], 'verbose_name': 'Karta Sai', 'verbose_name_plural': 'Karta Sai'},
        ),
        migrations.AlterModelOptions(
            name='persuratanportal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Portal Karta (UI)', 'verbose_name_plural': 'Portal Karta (UI)'},
        ),
        migrations.AlterModelOptions(
            name='reviewstep',
            options={'ordering': ['order'], 'verbose_name': 'Passu Revisaun', 'verbose_name_plural': 'Passu Revisaun'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=255, upload_to=core.models.upload_attachment_file, verbose_name='Ficheiru'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulu'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Hatutu'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Hatutun husi'),
        ),
        migrations.AlterField(
            model_name='classificationtag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Naran Klasifikasaun'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='allow_parallel',
            field=models.BooleanField(default=True, verbose_name='Paralelu?'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kria iha'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data-limite'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='core.incomingletter', verbose_name='Karta'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='note',
            field=models.TextField(blank=True, verbose_name='Observasaun / Nota'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.disposition', verbose_name='Dispozisaun Aman'),
        ),
        migrations.AlterField(
            model_name='disposition',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispo_sent', to=settings.AUTH_USER_MODEL, verbose_name="Hato'o husi"),
        ),
        migrations.AlterField(
            model_name='dispositionassignment',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispo_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Destinatáriu / Responsável'),
        ),
        migrations.AlterField(
            model_name='dispositionassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kompleta iha'),
        ),
        migrations.AlterField(
            model_name='dispositionassignment',
            name='disposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.disposition', verbose_name='Dispozisaun'),
        ),
        migrations.AlterField(
            model_name='dispositionassignment',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lee iha'),
        ),
        migrations.AlterField(
            model_name='expeditionrecord',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipu Kontentu'),
        ),
        migrations.AlterField(
            model_name='expeditionrecord',
            name='destination',
            field=models.CharField(max_length=255, verbose_name='Destino / Destinatáriu'),
        ),
        migrations.AlterField(
            model_name='expeditionrecord',
            name='method',
            field=models.CharField(choices=[('email', 'Email'), ('fisik', 'Fíziku')], default='email', max_length=20, verbose_name='Metodu'),
        ),
        migrations.AlterField(
            model_name='expeditionrecord',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='ID Objetu'),
        ),
        migrations.AlterField(
            model_name='expeditionrecord',
            name='proof_file',
            field=models.FileField(blank=True, upload_to='expedition/proofs/%Y/%m/', verbose_name='Prova / Evidénsia'),
        ),
        migrations.AlterField(
            model_name='expeditionrecord',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Simu'),
        ),
        migrations.AlterField(
            model_name='expeditionrecord',
            name='received_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Recebe husi'),
        ),
        migrations.AlterField(
            model_name='expeditionrecord',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Haruka'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kria iha'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='doc_type',
            field=models.CharField(choices=[('ND', 'Nota Dinas'), ('UD', 'Konvite / Convite'), ('ST', 'Karta Servisu / Ofício'), ('MM', 'Memo'), ('LN', 'Seluk / Outro')], default='ND', max_length=2, verbose_name='Tipu Dokumentu'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='file',
            field=models.FileField(upload_to='incoming/followups/%Y/%m/', verbose_name='Ficheiru'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='core.incomingletter', verbose_name='Karta'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulu'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='agenda_number',
            field=models.CharField(blank=True, help_text="Hari'i automátiku bainhira rejistu primeiru.", max_length=30, unique=True, verbose_name='Númeru Agenda'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='core.attachment', verbose_name='Anexu'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='barcode_image',
            field=models.ImageField(blank=True, upload_to='incoming/barcodes/', verbose_name='Kódigu Barra'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='classification_tags',
            field=models.ManyToManyField(blank=True, to='core.classificationtag', verbose_name='Klasifikasaun'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kria iha'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_created', to=settings.AUTH_USER_MODEL, verbose_name='Rejista husi'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='current_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handling_letters', to=settings.AUTH_USER_MODEL, verbose_name='Responsável (agora)'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='disposed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data Arkivu'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='origin',
            field=models.CharField(max_length=255, verbose_name='Karta Husi'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='origin_date',
            field=models.DateField(verbose_name='Data Karta Oríjém'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='origin_number',
            field=models.CharField(max_length=100, verbose_name='Númeru Oríjém'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='priority',
            field=models.CharField(choices=[('B', 'Básiku / Normal'), ('S', 'Urjente / Urgente'), ('SS', 'Muitu Urjente / Muito Urgente')], default='B', max_length=2, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='incoming/qrcodes/', verbose_name='QR Kode'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='received_via',
            field=models.CharField(choices=[('fisik', 'Fíziku'), ('email', 'Email')], default='fisik', max_length=10, verbose_name='Tama via'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='retention_class',
            field=models.CharField(blank=True, help_text='Kode retensaun (JRA, dll.)', max_length=50, verbose_name='Klas Retensaun'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='retention_until',
            field=models.DateField(blank=True, null=True, verbose_name="To'o data"),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='scan_pdf',
            field=models.FileField(blank=True, help_text='Rezultadu skaneamuntu (PDF)', max_length=255, upload_to=core.models.upload_incoming_scan, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Scan PDF'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunhu'), ('REG', 'Rejistu'), ('DISP', 'Dispozisaun'), ('PROG', 'Iha Prosesu / Em Progresso'), ('DONE', 'Remata / Finaliza'), ('ARCH', 'Arkivu / Arquivo')], default='REG', max_length=5, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='subject',
            field=models.CharField(max_length=300, verbose_name='Asuntu'),
        ),
        migrations.AlterField(
            model_name='incomingletter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualiza iha'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='core.attachment', verbose_name='Anexu'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='body',
            field=models.TextField(verbose_name='Konteúdu'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kria iha'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_created', to=settings.AUTH_USER_MODEL, verbose_name='Kria husi'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='number',
            field=models.CharField(blank=True, help_text='Sei tau automátiku bainhira estadu FINAL (númeru rai).', max_length=40, unique=True, verbose_name='Númeru'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='outgoing/qrcodes/%Y/%m/', verbose_name='QR Kode'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='retention_class',
            field=models.CharField(blank=True, max_length=50, verbose_name='Klas Retensaun'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='retention_until',
            field=models.DateField(blank=True, null=True, verbose_name="To'o data"),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='signed_pdf',
            field=models.FileField(blank=True, max_length=255, upload_to=core.models.upload_outgoing_signed, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF Asina / TTE'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunhu'), ('REVIEW', 'Revizaun / Paraf'), ('APPROVED', 'Aprovadu / Aprovado'), ('FINAL', 'Final (Númeru Rai)'), ('SENT', 'Haruka / Enviado'), ('ARCH', 'Arkivu / Arquivo')], default='DRAFT', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='subject',
            field=models.CharField(max_length=300, verbose_name='Asuntu / Assunto'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='template_type',
            field=models.CharField(choices=[('ND', 'Nota Dinas'), ('UD', 'Konvite / Convite'), ('ST', 'Karta Servisu / Ofício'), ('MM', 'Memo'), ('LN', 'Seluk / Outro')], default='ND', max_length=2, verbose_name='Template / Formuláriu'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualiza iha'),
        ),
        migrations.AlterField(
            model_name='reviewstep',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprova iha'),
        ),
        migrations.AlterField(
            model_name='reviewstep',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.outgoingletter', verbose_name='Karta'),
        ),
        migrations.AlterField(
            model_name='reviewstep',
            name='note',
            field=models.CharField(blank=True, max_length=300, verbose_name='Observasaun'),
        ),
        migrations.AlterField(
            model_name='reviewstep',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Passu #'),
        ),
        migrations.AlterField(
            model_name='reviewstep',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Revisor / Paraf'),
        ),
    ]
