# Generated by Django 5.2.7 on 2025-10-21 08:54

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_alter_attachment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupu',
            fields=[
            ],
            options={
                'verbose_name': 'Grupu',
                'verbose_name_plural': 'Grupu',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Uzuariu',
            fields=[
            ],
            options={
                'verbose_name': 'Uzuáriu',
                'verbose_name_plural': 'Uzuáriu',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='dispositionassignment',
            options={'ordering': ['assignee__username'], 'verbose_name': 'Distribuisaun Dispozisaun', 'verbose_name_plural': 'Distribuisaun'},
        ),
        migrations.AlterField(
            model_name='followup',
            name='doc_type',
            field=models.CharField(choices=[('ND', 'Nota Servisu'), ('UD', 'Konvite / Convite'), ('ST', 'Karta Servisu / Ofício'), ('MM', 'Memo'), ('LN', 'Seluk / Outro')], default='ND', max_length=2, verbose_name='Tipu Dokumentu'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='template_type',
            field=models.CharField(choices=[('ND', 'Nota Servisu'), ('UD', 'Konvite / Convite'), ('ST', 'Karta Servisu / Ofício'), ('MM', 'Memo'), ('LN', 'Seluk / Outro')], default='ND', max_length=2, verbose_name='Template / Formuláriu'),
        ),
        migrations.CreateModel(
            name='DestructionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Alasan')),
                ('destroyed_at', models.DateField(blank=True, null=True, verbose_name='Dimusnahkan pada')),
                ('document', models.FileField(blank=True, upload_to='destruction/%Y/%m/', verbose_name='Berita Acara (PDF)')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Disetujui oleh')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Pemusnahan Arsip',
                'verbose_name_plural': 'Pemusnahan Arsip',
                'ordering': ['-destroyed_at'],
            },
        ),
    ]
