# Generated by Django 5.2.7 on 2025-10-22 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_grupu_uzuariu_alter_dispositionassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destructionrecord',
            options={'ordering': ['-destroyed_at'], 'verbose_name': 'Destruisaun Arkivu', 'verbose_name_plural': 'Destruisaun Arkivu'},
        ),
        migrations.AlterField(
            model_name='destructionrecord',
            name='object_id',
            field=models.PositiveIntegerField(db_column='object_id'),
        ),
        migrations.RenameField(
            model_name='destructionrecord',
            old_name='object_id',
            new_name='objetu_id',
        ),
        migrations.RenameField(
            model_name='destructionrecord',
            old_name='content_type',
            new_name='tipu_konteúdu_id',
        ),
        migrations.AlterField(
            model_name='destructionrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aprova ona husi'),
        ),
        migrations.AlterField(
            model_name='destructionrecord',
            name='destroyed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Destroi iha'),
        ),
        migrations.AlterField(
            model_name='destructionrecord',
            name='document',
            field=models.FileField(blank=True, upload_to='destruction/%Y/%m/', verbose_name='Notisia (PDF)'),
        ),
        migrations.AlterField(
            model_name='destructionrecord',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Razaun'),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunhu'), ('REVIEW', 'Revizaun / Paraf'), ('APPROVED', 'Aprovadu / Aprovado'), ('FINAL', 'Final (Númeru Rai)'), ('SENT', 'Manda / Enviado'), ('ARCH', 'Arkivu / Arquivo')], default='DRAFT', max_length=10, verbose_name='Estado'),
        ),
    ]
