"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%k@i9xxuzc5_5tgx$pd-vkl2w!e)-*ct5po!hs4hn&v!%v3x+o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# (Optional Dev) If you access via a browser app/proxy
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]

# Application definition
INSTALLED_APPS = [
    "jazzmin",  # Jazzmin must be before django.contrib.admin

    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # 3rd party
    "crispy_forms",
    "crispy_bootstrap5",
    "rest_framework",
    "django_filters",

    # Local apps
    "core",
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"simple": {"format": "%(asctime)s %(levelname)s %(message)s"}},
    "handlers": {
        "audit_file": {
            "class": "logging.FileHandler",
            "filename": str(BASE_DIR / "audit.log"),
            "formatter": "simple",
        }
    },
    "loggers": {
        "audit": {"handlers": ["audit_file"], "level": "INFO", "propagate": False},
    },
}

PUBLIC_BASE_URL = ""
PUBLIC_VERIFY_BASE = "/verify/"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.AuditViewMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,   
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "tet"        
TIME_ZONE = "Asia/Dili"
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ("tet", "Tetun"),
    ("pt",  "Português"),
    ("en",  "English"),
]

# Folder for translation (*.po/*.mo)
LOCALE_PATHS = [BASE_DIR / "locale"]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "core" / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media (uploads) for scanned letters, attachments, etc.
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework defaults (useful soon for API endpoints)
REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

# ============== JAZZMIN ==============
JAZZMIN_SETTINGS = {
    "site_title": "Sistema Karta Kabinete",
    "site_header": "Sistema Karta Kabinete",
    "site_brand": "DASHBOARD",
    # "site_logo": "core/img/logo.png",

    "welcome_sign": "Bem-vindu ba Admin Sistema Karta",
    "show_sidebar": True,
    "navigation_expanded": True,

    # ===== Bar Leten
    "topmenu_links": [
        # Tampilkan hanya nama brand di bar atas, link ke dashboard admin bawaan
        {"name": "TIC TIMOR", "url": "admin:index", "icon": "fas fa-building"},
    ],

    # ===== Menu user leten los
    "usermenu_links": [
        {"name": "Karta Tama", "url": "admin_incoming_list"},
        {"name": "Karta Sai", "url": "admin_outgoing_list"},
    ],

    # Urutan app/model di sidebar
    "order_with_respect_to": [
        "core",
        "core.IncomingLetter",
        "core.Disposition",
        "core.DispositionAssignment",
        "core.FollowUp",
        "core.OutgoingLetter",
        "core.ReviewStep",
        "core.ExpeditionRecord",
        "core.ClassificationTag",
        "core.Attachment",
        "core.Grupu",
        "core.Uzuariu",
    ],

    # Ikon menu
    "icons": {
        # Proxy auth (lihat admin.py)
        "core.Grupu": "fas fa-users",
        "core.Uzuariu": "fas fa-user",

        "core.PersuratanPortal": "fas fa-th-large",
        "core.IncomingLetter": "fas fa-inbox",
        "core.Disposition": "fas fa-share-square",
        "core.DispositionAssignment": "fas fa-user-check",
        "core.FollowUp": "fas fa-tasks",
        "core.OutgoingLetter": "fas fa-paper-plane",
        "core.ReviewStep": "fas fa-stream",
        "core.ExpeditionRecord": "fas fa-shipping-fast",
        "core.ClassificationTag": "fas fa-tags",
        "core.Attachment": "fas fa-paperclip",
    },

    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-file-alt",
}

# CSS/JS + per-model tabs + util Jazzmin
JAZZMIN_SETTINGS.update({
    # aset kustom
    "custom_css": "core/css/admin_surat.css",
    "custom_js": "core/js/admin_surat.js",

    # format change_form khusus per model (tabs untuk Karta Tama)
    "changeform_format_overrides": {
        "core.incomingletter": "horizontal_tabs",  # Form "Karta Tama" pakai tab
        # "core.outgoingletter": "horizontal_tabs",  # (opsional) aktifkan juga untuk Karta Sai
    },

    # modal tambah/edit untuk field relasi (FK/M2M) agar alur input cepat
    "related_modal_active": True,

    # sembunyikan proxy "Portal Karta (UI)" dari menu
    "hide_models": ["core.persuratanportal"],
})


JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "navbar": "navbar-dark bg-dark",
    "navbar_fixed": True,
    "sidebar": "dark",
    "sidebar_fixed": True,
    "no_navbar_border": True,
    "sidebar_nav_flat_style": True,
    "sidebar_nav_child_indent": True,
}

LOGIN_URL = "ui_login"
LOGIN_REDIRECT_URL = "/admin/persuratan/"
LOGOUT_REDIRECT_URL = "ui_login"